/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NXF1_V1_UART_DATA_PB_H_INCLUDED
#define PB_NXF1_V1_UART_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Common enums */
typedef enum _nxf1_v1_CommandType {
    nxf1_v1_CommandType_CMD_UNSPECIFIED = 0,
    nxf1_v1_CommandType_CMD_PING = 1,
    nxf1_v1_CommandType_CMD_INJECT = 2,
    nxf1_v1_CommandType_CMD_ABORT = 3,
    nxf1_v1_CommandType_CMD_ARM = 4
} nxf1_v1_CommandType;

typedef enum _nxf1_v1_InjectionType {
    nxf1_v1_InjectionType_INJ_UNSPECIFIED = 0,
    nxf1_v1_InjectionType_INJ_BYTE_DROP = 1,
    nxf1_v1_InjectionType_INJ_BIT_FLIP = 2,
    nxf1_v1_InjectionType_INJ_PHANTOM_BYTE = 3
} nxf1_v1_InjectionType;

typedef enum _nxf1_v1_ExecStatus {
    nxf1_v1_ExecStatus_STATUS_UNSPECIFIED = 0,
    nxf1_v1_ExecStatus_STATUS_ACCEPTED = 1,
    nxf1_v1_ExecStatus_STATUS_REJECTED = 2,
    nxf1_v1_ExecStatus_STATUS_RUNNING = 3,
    nxf1_v1_ExecStatus_STATUS_DONE = 4,
    nxf1_v1_ExecStatus_STATUS_ERROR = 5
} nxf1_v1_ExecStatus;

typedef enum _nxf1_v1_TestVerdict {
    nxf1_v1_TestVerdict_VERDICT_UNSET = 0,
    nxf1_v1_TestVerdict_VERDICT_PASS = 1,
    nxf1_v1_TestVerdict_VERDICT_FAIL = 2
} nxf1_v1_TestVerdict;

typedef enum _nxf1_v1_BitFlipMode {
    nxf1_v1_BitFlipMode_BITFLIP_RANDOM = 0,
    nxf1_v1_BitFlipMode_BITFLIP_PERIODIC = 1
} nxf1_v1_BitFlipMode;

typedef enum _nxf1_v1_PhantomByteMode {
    nxf1_v1_PhantomByteMode_PHANTOM_RANDOM = 0,
    nxf1_v1_PhantomByteMode_PHANTOM_MANUAL = 1
} nxf1_v1_PhantomByteMode;

typedef enum _nxf1_v1_TransportType {
    nxf1_v1_TransportType_TRANSPORT_UNSPECIFIED = 0,
    nxf1_v1_TransportType_TRANSPORT_UART = 1,
    nxf1_v1_TransportType_TRANSPORT_MODBUS = 2,
    nxf1_v1_TransportType_TRANSPORT_I2C = 3
} nxf1_v1_TransportType;

/* Struct definitions */
/* Per-injection parameter blocks */
typedef struct _nxf1_v1_ByteDropParams {
    uint32_t start_offset; /* where to begin dropping in the stream/frame */
    uint32_t length; /* you just added “any length” – define max */
    char payload[512];
} nxf1_v1_ByteDropParams;

typedef struct _nxf1_v1_BitFlipParams {
    uint32_t every_n_p; /* if periodic, every_n bits to drop */
    uint32_t bits_drop; /* bits to drop randomly */
    char payload[512]; /* the message */
    nxf1_v1_BitFlipMode mode; /* mode */
} nxf1_v1_BitFlipParams;

typedef struct _nxf1_v1_PhantomByteParams {
    uint32_t offset;
    uint32_t byte_value;
    char payload[512];
    nxf1_v1_PhantomByteMode mode;
} nxf1_v1_PhantomByteParams;

/* Host -> DSI */
typedef struct _nxf1_v1_DsiCommand {
    uint32_t proto_version; /* e.g., 1 */
    uint32_t id; /* your correlation/sequence id */
    nxf1_v1_CommandType cmd; /* inject, abort, ping, cmd_inject for bytedrop and bitflip */
    nxf1_v1_InjectionType inj_type; /* required if cmd == CMD_INJECT */
    nxf1_v1_TransportType transport; /* which transport protocol to be used */
    uint32_t duration_ms; /* 0 means “until complete/next command” */
    double sensor_value;
    pb_size_t which_params;
    union {
        nxf1_v1_ByteDropParams byte_drop;
        nxf1_v1_BitFlipParams bit_flip;
        nxf1_v1_PhantomByteParams phantom_byte;
    } params;
} nxf1_v1_DsiCommand;

/* DSI/TMI -> Host (immediate ACK) */
typedef struct _nxf1_v1_DsiAck {
    uint32_t id; /* echoes DsiCommand.id */
    nxf1_v1_ExecStatus status; /* ACCEPTED/REJECTED/RUNNING */
    uint32_t error_code; /* 0 if ok; else reason (enum/table in docs) */
} nxf1_v1_DsiAck;

typedef struct _nxf1_v1_TelemetryChunk {
    uint32_t chunk_index; /* 0..N-1 */
    uint32_t chunk_total; /* N */
    pb_callback_t payload; /* bounded (e.g., <= 512B for UART) */
    uint32_t crc32; /* of payload for transport sanity */
} nxf1_v1_TelemetryChunk;

/* DSI/TMI -> Host (final report) */
typedef struct _nxf1_v1_TmiReport {
    uint32_t id; /* echoes DsiCommand.id */
    nxf1_v1_ExecStatus status; /* DONE or ERROR */
    nxf1_v1_TestVerdict verdict; /* PASS/FAIL if you can decide on-box */
    uint32_t ts_start_ms; /* uptime ms */
    uint32_t ts_end_ms;
    /* basic metrics */
    uint32_t bytes_tx;
    uint32_t bytes_rx;
    uint32_t bytes_dropped;
    uint32_t bytes_flipped;
    /* optional raw telemetry (chunked) */
    bool has_chunk;
    nxf1_v1_TelemetryChunk chunk;
} nxf1_v1_TmiReport;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _nxf1_v1_CommandType_MIN nxf1_v1_CommandType_CMD_UNSPECIFIED
#define _nxf1_v1_CommandType_MAX nxf1_v1_CommandType_CMD_ARM
#define _nxf1_v1_CommandType_ARRAYSIZE ((nxf1_v1_CommandType)(nxf1_v1_CommandType_CMD_ARM+1))

#define _nxf1_v1_InjectionType_MIN nxf1_v1_InjectionType_INJ_UNSPECIFIED
#define _nxf1_v1_InjectionType_MAX nxf1_v1_InjectionType_INJ_PHANTOM_BYTE
#define _nxf1_v1_InjectionType_ARRAYSIZE ((nxf1_v1_InjectionType)(nxf1_v1_InjectionType_INJ_PHANTOM_BYTE+1))

#define _nxf1_v1_ExecStatus_MIN nxf1_v1_ExecStatus_STATUS_UNSPECIFIED
#define _nxf1_v1_ExecStatus_MAX nxf1_v1_ExecStatus_STATUS_ERROR
#define _nxf1_v1_ExecStatus_ARRAYSIZE ((nxf1_v1_ExecStatus)(nxf1_v1_ExecStatus_STATUS_ERROR+1))

#define _nxf1_v1_TestVerdict_MIN nxf1_v1_TestVerdict_VERDICT_UNSET
#define _nxf1_v1_TestVerdict_MAX nxf1_v1_TestVerdict_VERDICT_FAIL
#define _nxf1_v1_TestVerdict_ARRAYSIZE ((nxf1_v1_TestVerdict)(nxf1_v1_TestVerdict_VERDICT_FAIL+1))

#define _nxf1_v1_BitFlipMode_MIN nxf1_v1_BitFlipMode_BITFLIP_RANDOM
#define _nxf1_v1_BitFlipMode_MAX nxf1_v1_BitFlipMode_BITFLIP_PERIODIC
#define _nxf1_v1_BitFlipMode_ARRAYSIZE ((nxf1_v1_BitFlipMode)(nxf1_v1_BitFlipMode_BITFLIP_PERIODIC+1))

#define _nxf1_v1_PhantomByteMode_MIN nxf1_v1_PhantomByteMode_PHANTOM_RANDOM
#define _nxf1_v1_PhantomByteMode_MAX nxf1_v1_PhantomByteMode_PHANTOM_MANUAL
#define _nxf1_v1_PhantomByteMode_ARRAYSIZE ((nxf1_v1_PhantomByteMode)(nxf1_v1_PhantomByteMode_PHANTOM_MANUAL+1))

#define _nxf1_v1_TransportType_MIN nxf1_v1_TransportType_TRANSPORT_UNSPECIFIED
#define _nxf1_v1_TransportType_MAX nxf1_v1_TransportType_TRANSPORT_I2C
#define _nxf1_v1_TransportType_ARRAYSIZE ((nxf1_v1_TransportType)(nxf1_v1_TransportType_TRANSPORT_I2C+1))

#define nxf1_v1_DsiCommand_cmd_ENUMTYPE nxf1_v1_CommandType
#define nxf1_v1_DsiCommand_inj_type_ENUMTYPE nxf1_v1_InjectionType
#define nxf1_v1_DsiCommand_transport_ENUMTYPE nxf1_v1_TransportType


#define nxf1_v1_BitFlipParams_mode_ENUMTYPE nxf1_v1_BitFlipMode

#define nxf1_v1_PhantomByteParams_mode_ENUMTYPE nxf1_v1_PhantomByteMode

#define nxf1_v1_DsiAck_status_ENUMTYPE nxf1_v1_ExecStatus

#define nxf1_v1_TmiReport_status_ENUMTYPE nxf1_v1_ExecStatus
#define nxf1_v1_TmiReport_verdict_ENUMTYPE nxf1_v1_TestVerdict



/* Initializer values for message structs */
#define nxf1_v1_DsiCommand_init_default          {0, 0, _nxf1_v1_CommandType_MIN, _nxf1_v1_InjectionType_MIN, _nxf1_v1_TransportType_MIN, 0, 0, 0, {nxf1_v1_ByteDropParams_init_default}}
#define nxf1_v1_ByteDropParams_init_default      {0, 0, ""}
#define nxf1_v1_BitFlipParams_init_default       {0, 0, "", _nxf1_v1_BitFlipMode_MIN}
#define nxf1_v1_PhantomByteParams_init_default   {0, 0, "", _nxf1_v1_PhantomByteMode_MIN}
#define nxf1_v1_DsiAck_init_default              {0, _nxf1_v1_ExecStatus_MIN, 0}
#define nxf1_v1_TmiReport_init_default           {0, _nxf1_v1_ExecStatus_MIN, _nxf1_v1_TestVerdict_MIN, 0, 0, 0, 0, 0, 0, false, nxf1_v1_TelemetryChunk_init_default}
#define nxf1_v1_TelemetryChunk_init_default      {0, 0, {{NULL}, NULL}, 0}
#define nxf1_v1_DsiCommand_init_zero             {0, 0, _nxf1_v1_CommandType_MIN, _nxf1_v1_InjectionType_MIN, _nxf1_v1_TransportType_MIN, 0, 0, 0, {nxf1_v1_ByteDropParams_init_zero}}
#define nxf1_v1_ByteDropParams_init_zero         {0, 0, ""}
#define nxf1_v1_BitFlipParams_init_zero          {0, 0, "", _nxf1_v1_BitFlipMode_MIN}
#define nxf1_v1_PhantomByteParams_init_zero      {0, 0, "", _nxf1_v1_PhantomByteMode_MIN}
#define nxf1_v1_DsiAck_init_zero                 {0, _nxf1_v1_ExecStatus_MIN, 0}
#define nxf1_v1_TmiReport_init_zero              {0, _nxf1_v1_ExecStatus_MIN, _nxf1_v1_TestVerdict_MIN, 0, 0, 0, 0, 0, 0, false, nxf1_v1_TelemetryChunk_init_zero}
#define nxf1_v1_TelemetryChunk_init_zero         {0, 0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define nxf1_v1_ByteDropParams_start_offset_tag  1
#define nxf1_v1_ByteDropParams_length_tag        2
#define nxf1_v1_ByteDropParams_payload_tag       3
#define nxf1_v1_BitFlipParams_every_n_p_tag      1
#define nxf1_v1_BitFlipParams_bits_drop_tag      2
#define nxf1_v1_BitFlipParams_payload_tag        3
#define nxf1_v1_BitFlipParams_mode_tag           4
#define nxf1_v1_PhantomByteParams_offset_tag     1
#define nxf1_v1_PhantomByteParams_byte_value_tag 2
#define nxf1_v1_PhantomByteParams_payload_tag    3
#define nxf1_v1_PhantomByteParams_mode_tag       4
#define nxf1_v1_DsiCommand_proto_version_tag     1
#define nxf1_v1_DsiCommand_id_tag                2
#define nxf1_v1_DsiCommand_cmd_tag               3
#define nxf1_v1_DsiCommand_inj_type_tag          4
#define nxf1_v1_DsiCommand_transport_tag         5
#define nxf1_v1_DsiCommand_duration_ms_tag       6
#define nxf1_v1_DsiCommand_sensor_value_tag      7
#define nxf1_v1_DsiCommand_byte_drop_tag         10
#define nxf1_v1_DsiCommand_bit_flip_tag          11
#define nxf1_v1_DsiCommand_phantom_byte_tag      12
#define nxf1_v1_DsiAck_id_tag                    1
#define nxf1_v1_DsiAck_status_tag                2
#define nxf1_v1_DsiAck_error_code_tag            3
#define nxf1_v1_TelemetryChunk_chunk_index_tag   1
#define nxf1_v1_TelemetryChunk_chunk_total_tag   2
#define nxf1_v1_TelemetryChunk_payload_tag       3
#define nxf1_v1_TelemetryChunk_crc32_tag         4
#define nxf1_v1_TmiReport_id_tag                 1
#define nxf1_v1_TmiReport_status_tag             2
#define nxf1_v1_TmiReport_verdict_tag            3
#define nxf1_v1_TmiReport_ts_start_ms_tag        4
#define nxf1_v1_TmiReport_ts_end_ms_tag          5
#define nxf1_v1_TmiReport_bytes_tx_tag           6
#define nxf1_v1_TmiReport_bytes_rx_tag           7
#define nxf1_v1_TmiReport_bytes_dropped_tag      8
#define nxf1_v1_TmiReport_bytes_flipped_tag      9
#define nxf1_v1_TmiReport_chunk_tag              20

/* Struct field encoding specification for nanopb */
#define nxf1_v1_DsiCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_version,     1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2) \
X(a, STATIC,   SINGULAR, UENUM,    cmd,               3) \
X(a, STATIC,   SINGULAR, UENUM,    inj_type,          4) \
X(a, STATIC,   SINGULAR, UENUM,    transport,         5) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       6) \
X(a, STATIC,   SINGULAR, DOUBLE,   sensor_value,      7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,byte_drop,params.byte_drop),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,bit_flip,params.bit_flip),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,phantom_byte,params.phantom_byte),  12)
#define nxf1_v1_DsiCommand_CALLBACK NULL
#define nxf1_v1_DsiCommand_DEFAULT NULL
#define nxf1_v1_DsiCommand_params_byte_drop_MSGTYPE nxf1_v1_ByteDropParams
#define nxf1_v1_DsiCommand_params_bit_flip_MSGTYPE nxf1_v1_BitFlipParams
#define nxf1_v1_DsiCommand_params_phantom_byte_MSGTYPE nxf1_v1_PhantomByteParams

#define nxf1_v1_ByteDropParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_offset,      1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2) \
X(a, STATIC,   SINGULAR, STRING,   payload,           3)
#define nxf1_v1_ByteDropParams_CALLBACK NULL
#define nxf1_v1_ByteDropParams_DEFAULT NULL

#define nxf1_v1_BitFlipParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   every_n_p,         1) \
X(a, STATIC,   SINGULAR, UINT32,   bits_drop,         2) \
X(a, STATIC,   SINGULAR, STRING,   payload,           3) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              4)
#define nxf1_v1_BitFlipParams_CALLBACK NULL
#define nxf1_v1_BitFlipParams_DEFAULT NULL

#define nxf1_v1_PhantomByteParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   byte_value,        2) \
X(a, STATIC,   SINGULAR, STRING,   payload,           3) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              4)
#define nxf1_v1_PhantomByteParams_CALLBACK NULL
#define nxf1_v1_PhantomByteParams_DEFAULT NULL

#define nxf1_v1_DsiAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        3)
#define nxf1_v1_DsiAck_CALLBACK NULL
#define nxf1_v1_DsiAck_DEFAULT NULL

#define nxf1_v1_TmiReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, UENUM,    verdict,           3) \
X(a, STATIC,   SINGULAR, UINT32,   ts_start_ms,       4) \
X(a, STATIC,   SINGULAR, UINT32,   ts_end_ms,         5) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_tx,          6) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_rx,          7) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_dropped,     8) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_flipped,     9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  chunk,            20)
#define nxf1_v1_TmiReport_CALLBACK NULL
#define nxf1_v1_TmiReport_DEFAULT NULL
#define nxf1_v1_TmiReport_chunk_MSGTYPE nxf1_v1_TelemetryChunk

#define nxf1_v1_TelemetryChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_total,       2) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           3) \
X(a, STATIC,   SINGULAR, UINT32,   crc32,             4)
#define nxf1_v1_TelemetryChunk_CALLBACK pb_default_field_callback
#define nxf1_v1_TelemetryChunk_DEFAULT NULL

extern const pb_msgdesc_t nxf1_v1_DsiCommand_msg;
extern const pb_msgdesc_t nxf1_v1_ByteDropParams_msg;
extern const pb_msgdesc_t nxf1_v1_BitFlipParams_msg;
extern const pb_msgdesc_t nxf1_v1_PhantomByteParams_msg;
extern const pb_msgdesc_t nxf1_v1_DsiAck_msg;
extern const pb_msgdesc_t nxf1_v1_TmiReport_msg;
extern const pb_msgdesc_t nxf1_v1_TelemetryChunk_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define nxf1_v1_DsiCommand_fields &nxf1_v1_DsiCommand_msg
#define nxf1_v1_ByteDropParams_fields &nxf1_v1_ByteDropParams_msg
#define nxf1_v1_BitFlipParams_fields &nxf1_v1_BitFlipParams_msg
#define nxf1_v1_PhantomByteParams_fields &nxf1_v1_PhantomByteParams_msg
#define nxf1_v1_DsiAck_fields &nxf1_v1_DsiAck_msg
#define nxf1_v1_TmiReport_fields &nxf1_v1_TmiReport_msg
#define nxf1_v1_TelemetryChunk_fields &nxf1_v1_TelemetryChunk_msg

/* Maximum encoded size of messages (where known) */
/* nxf1_v1_TmiReport_size depends on runtime parameters */
/* nxf1_v1_TelemetryChunk_size depends on runtime parameters */
#define NXF1_V1_UART_DATA_PB_H_MAX_SIZE          nxf1_v1_DsiCommand_size
#define nxf1_v1_BitFlipParams_size               528
#define nxf1_v1_ByteDropParams_size              526
#define nxf1_v1_DsiAck_size                      14
#define nxf1_v1_DsiCommand_size                  564
#define nxf1_v1_PhantomByteParams_size           528

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
