/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "uart_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxf1_v1_DsiCommand, nxf1_v1_DsiCommand, 2)


PB_BIND(nxf1_v1_ByteDropParams, nxf1_v1_ByteDropParams, 2)


PB_BIND(nxf1_v1_BitFlipParams, nxf1_v1_BitFlipParams, 2)


PB_BIND(nxf1_v1_PhantomByteParams, nxf1_v1_PhantomByteParams, 2)


PB_BIND(nxf1_v1_DsiAck, nxf1_v1_DsiAck, AUTO)


PB_BIND(nxf1_v1_TmiReport, nxf1_v1_TmiReport, AUTO)


PB_BIND(nxf1_v1_TelemetryChunk, nxf1_v1_TelemetryChunk, AUTO)

















#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

