/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "uart_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(test_msgs_UART_Channels, test_msgs_UART_Channels, AUTO)


PB_BIND(test_msgs_Error_Message, test_msgs_Error_Message, AUTO)



