/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "uart_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nxf1_v1_DsiCommand, nxf1_v1_DsiCommand, 2)


PB_BIND(nxf1_v1_ByteDropParams, nxf1_v1_ByteDropParams, 2)


PB_BIND(nxf1_v1_BitFlipParams, nxf1_v1_BitFlipParams, 2)


PB_BIND(nxf1_v1_PhantomByteParams, nxf1_v1_PhantomByteParams, AUTO)


PB_BIND(nxf1_v1_DsiAck, nxf1_v1_DsiAck, AUTO)


PB_BIND(nxf1_v1_TmiReport, nxf1_v1_TmiReport, AUTO)


PB_BIND(nxf1_v1_TelemetryChunk, nxf1_v1_TelemetryChunk, AUTO)













